[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quantax"
version = "0.3.0"
description = "Flexible neural quantum states based on JAX"
authors = [
    { name = "Ao Chen", email = "chenao.phys@gmail.com" },
    { name = "Christopher Roth" }
]
requires-python = ">=3.11,<=3.13"
dependencies = [
    "numpy>=2.0.0",
    "scipy>=1.14.0",
    "jax>=0.8.0",
    "equinox>=0.11.4",
    "lrux>=0.1.0",
]

[project.optional-dependencies]
full = [
    "numpy>=2.0.0",
    "scipy>=1.14.0",
    "matplotlib>=3.8.0",
    "quspin>=1.0.0",
    "jax>=0.8.0",
    "equinox>=0.11.4",
    "lineax>=0.1.0",
    "lrux>=0.1.0",
    "jaxmg>=0.0.6",
]
docs = [
    "sphinx",
    "myst-nb",
    "pydata-sphinx-theme",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["quantax*"]

[tool.black]
target-version = ["py311", "py312", "py313"]

[tool.pyright]
include = ["quantax"]
pythonVersion = "3.12"
typeCheckingMode = "standard"

